### ISSUE TITLE
Please help: can't find the file docs.txt 

### ISSUE THREAD

**Issue by teng1996** [morningmoni/HiLAP#1]
I want to run this model with rcv1 dataset. I have downloaded all needed file at http://www.ai.mit.edu/projects/jmlr/papers/volume5/lewis04a/lyrl2004_rcv1v2_README.htm. But I don't know how to get the file docs.txt. Could you please tell me how to get this file or provide download link? 
Thank you so much!

**Comment by morningmoni** [comment]
Thanks. Please try this: https://trec.nist.gov/data/reuters/reuters.html
