### ISSUE TITLE
Missing docs.txt file for reading rcv1 data

### ISSUE THREAD

**Issue by Lydiasc34** [morningmoni/HiLAP#10]
Hi, 

First of all, thank you for providing the code. I am looking at it for learning purpose. I found in readData_rcv1.py there is a need to get rcv text data. However, I could not find the 'docs.txt' in the hyperlink that you provided in the description. I wonder where to get the raw text data. Thanks.

**Comment by morningmoni** [comment]
Hi, you can get the raw text here https://trec.nist.gov/data/reuters/reuters.html

**Comment by wandli** [comment]
Hello, thank you for providing the code and link. But which one of the corpus in the link is the 'docs.txt'？

**Comment by Perfect0530** [comment]
> Hello, thank you for providing the code and link. But which one of the corpus in the link is the 'docs.txt'？


Did you finally got this document?

**Comment by wandli** [comment]
No
________________________________

**Comment by jayshanker2000** [comment]
Hi @morningmoni, it's still not clear where can we find the `docs.txt` file used in RCV1 dataset.
Can you share some more info on it?

Thank You
