### ISSUE TITLE
Error running "readData_yelp.py"

### ISSUE THREAD

**Issue by caruofc** [morningmoni/HiLAP#17]
This is what I am getting when I ran "readData_yelp.py"

```
Traceback (most recent call last):
  File "C:/HiLAP-master/readData_yelp.py", line 75, in <module>
    read_yelp()
TypeError: read_yelp() missing 1 required positional argument: 'root'

Process finished with exit code 1
```

The def of read_yelp() function is
`def read_yelp(root, min_reviews=1, max_reviews=10):`

So, it seems the function expects a parameter called "root". But when calling the function in line# 75 in main(), this parameter is not specified. Is it a bug?

**Comment by morningmoni** [comment]
Please do not run readData_yelp.py directly. It's used when loading data
<img width="619" alt="image" src="https://user-images.githubusercontent.com/8191712/185527650-6fc89eea-871a-4f58-b5b1-3d3ce99f2949.png">
