### ISSUE TITLE
cannot run Yelp dataset

### ISSUE THREAD

**Issue by lanliliana** [morningmoni/HiLAP#4]
I ’m trying to run the model with the Yelp dataset. I ’ve downloaded the dataset from https://www.yelp.com/dataset/challenge. (The file name: "yelp_dataset")
However, I cannot run the program "readData_yelp.py".
Since the code opens two files ( line 9:'yelp / Taxonomy_100' ； line 34: ’'yelp / yelp_data_100.csv') which I couldn't understand where do they come from.
Am I missing any steps to get these files? I cannot find any code to generate those two files from the original yelp dataset.

Thank you for all your assistance.

**Comment by morningmoni** [comment]
Hi, I added the yelp taxonomy (yelp/Taxonomy_100) I used in the experiment. For the yelp/yelp_data_100.csv, it consists of yelp businesses and their categories. I provided a two-line sample file in the same folder (since it's too big). They were generated from the original Yelp dataset and you can generate them yourself by following the same format. Note that the Yelp dataset each year is (slightly?) different though. Let me know if you have other questions.

**Comment by liuyijiang1994** [comment]
@morningmoni  Hi moni, the Yelp dataset each year is different as you said, could you please provide me a copy of the csv file used in your word?  The only version I can download is from Kaggle, which may be VERY different from the version you used. Thanks a lot!
Could you please upload it to Google drive or Baidu Net Disk, or send it directly to my email: cslyj@whu.edu.cn Ii it's convenient? 
Thanks a lot!

**Comment by DanqingZ** [comment]
@morningmoni Hi, I was using the yelp dataset from Kaggle (https://www.kaggle.com/yelp-dataset/yelp-dataset/version/6?select=yelp_review.csv). I have some question how you created the training and validation dataset. I loaded the yelp_review.csv file and it has 5261668 reviews. I believe you joined the review and the business csv files to create the yelp_data_100.csv file. However, the size of training, validation and testing data sets are 87375, 8737, 37265 as reported in the paper. This is not consistent with the original data set size. Could you give me some suggestions how you created the yelp_data_100.csv file from the yelp_review.csv file? If I am not using the correct version of the yelp dataset, could you let me know which version you are using for your experiment? Thanks a lot!
