### ISSUE TITLE
Questions about the calculation of Micro_f1 and Macro_f1

### ISSUE THREAD

**Issue by yuerxin1997** [morningmoni/HiLAP#5]
Hi there,
    I read your code, I am curious about the method of calculating the F1. For each label in the pred_label and true_label set, you put all the ancestor label into both the pred_label and true_label set,and then you calculation the f1_aa_micro and f1_aa_macro.
  I want to know why you do that?

THANKS!

**Comment by morningmoni** [comment]
This is because for some models we filtered the labels to the lowest labels during training (try searching "filter_ancestors"). During evaluation we used the original labels.

**Comment by yuerxin1997** [comment]
Ok,I got it. Thank you for the reply!
