### ISSUE TITLE
Question about RCV1 dataset

### ISSUE THREAD

**Issue by erichen510** [morningmoni/HiLAP#8]
When I did the experiment on RCV1, while textcnn reach the similar result in your paper. The performance of the BERT model got a big gap, about 10% lower, comparing with another unpublished paper's result.

For the file **lyrl2004_tokens_train.dat.gz**, do I need some additional preprocessing since the texts in the file are unreadable.

Thanks~

**Comment by morningmoni** [comment]
lyrl2004_tokens_train.dat.gz looks like the processed file for RCV1. I think you can get the raw dataset here: https://trec.nist.gov/data/reuters/reuters.html

**Comment by erichen510** [comment]
Thank you so much!
