### ISSUE TITLE
Question about yelp dataset

### ISSUE THREAD

**Issue by erichen510** [morningmoni/HiLAP#9]
We download _yelp_academic_dataset_review.json_ from the official site, and we got 8021121 reviews. However, I saw the review number is 5261668 based on the file _yelp_review.csv_. Could you tell me the number of reviews in your _yelp_data_100.csv_ files, or maybe provide the download link or file? Since we only can sample 78336 and 33700 for training and testing sets. Thank you in advance~

**Comment by morningmoni** [comment]
Hi, there have been quite a few ppl requesting it and I don't know if I have replied to you via email... If not, feel free to send me an email for more details. (closing this
